#!/usr/bin/env zsh

DOTFILES_REPO_NWO="tylerbodway/dotfiles"
DOTFILES_DIR="${HOME}/.dotfiles"

export TERM="xterm-256color"
BOLD="$(tput bold)"
DIM="$(tput dim)"
NC="$(tput sgr0)"

step() {
  local message=$1
  echo -e "\n💻 ${BOLD}${message}${NC}..."
}

run() {
  local cmd=$1
  echo "${DIM}\$ ${cmd}${NC}"
  eval "${cmd}"
}

step "Installing Xcode Command Line Tools for Git"
run 'xcode-select --install'
# Wait until Xcode Command Line Tools is finished installing
until $(xcode-select --print-path &> /dev/null); do
  sleep 5;
done

step "Installing Homebrew for OS packages and applications"
run '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'

step "Ensuring brew command is available"
run 'eval "$(/opt/homebrew/bin/brew shellenv)"'

step "Setting up dotfiles repository"
run "git clone https://github.com/${DOTFILES_REPO_NWO}.git ${DOTFILES_DIR}"
run "cd ${DOTFILES_DIR}"
run "git remote set-url origin git@github.com:${DOTFILES_REPO_NWO}.git"
run 'git submodule update --init --recursive'

step "Running installation script"
run './install'

step "Cleaning ZSH files"
run 'rm ~/.zsh_history'
run 'rm -rf ~/.zsh_sessions'
