#!/usr/bin/env bash

set -e


CONFIG="install.conf.yaml"
DOTBOT_DIR="gitmodules/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/bin/dotbot" --base-directory "${BASEDIR}" --config-file "${CONFIG}" --plugin-dir "gitmodules/dotbot-brew" "${@}"