#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_DIR="gitmodules/dotbot"
DOTBOT_BIN="bin/dotbot"
DOTBOT="${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}"

DOTBOT_BREW_DIR="gitmodules/dotbot-brew"

PROFILES_DIR="profiles"
PROFILE=${1:-mac}
PROFILE_DIR="${PROFILES_DIR}/${PROFILE}"

BASE_CONFIG=$(cat "${BASEDIR}/install.conf.yaml")
PROFILE_CONFIG=$(cat "${BASEDIR}/${PROFILE_DIR}/install.conf.yaml")
COMBINED_CONFIG="${BASE_CONFIG}\n${PROFILE_CONFIG}"
CONFIG="${COMBINED_CONFIG//@/${PROFILE_DIR}}"

cd "${BASEDIR}"
git submodule update --init --recursive --remote

"${DOTBOT}" -d "${BASEDIR}" --plugin-dir "${DOTBOT_BREW_DIR}" -c <(echo -e "$CONFIG") "${@:2}"
