alias pbst="pco cloud-box start"
alias pbsp="pco cloud-box stop"
alias pbh="pco cloud-box update-hosts"
alias pbip="pco cloud-box allow-my-ip"

# quits zellij before opening ssh which will open its own zellij
alias pbsh="wezterm cli spawn -- pco cloud-box ssh"
alias pbup="pbst && pbip && pbh && pbsh"

alias pb-nuke="pco cloud-box nuke --skip-confirm"
alias pb-prov="pco cloud-box provision --auto --fast"
alias pbn="pb-nuke && pb-prov && rm ~/.ssh/known_hosts ~/.ssh/known_hosts.old"
