gui:
  # do not show a warning when discarding changes in the staging view.
  skipDiscardChangeWarning: true

  # do not show warning when applying/popping the stash
  skipStashWarning: true

  # do not show a warning when attempting to commit without any staged files; instead stage all unstaged files.
  skipNoStagedFilesWarning: true

  # fraction of the total screen width to use for the left side section. number from 0 to 1.0.
  sidePanelWidth: 0.3

  # increase the height of the focused side window; creating an accordion effect.
  expandFocusedSidePanel: true

  # nerd fonts version to use. one of: '2' | '3' | empty string (default / no icons)
  nerdFontsVersion: "3"

  # length of commit hash in commits view.
  commitHashLength: 7 # matches GitHub

  # Height of the command log view
  commandLogSize: 6

  # display the files as a flat list. this can still be toggled with the backtick key.
  showFileTree: false

  # catppuccin-mocha
  theme:
    activeBorderColor:
      - "#a6e3a1"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#a6e3a1"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#eef1fc"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"

# don't display introductory popups upon opening lazygit.
disableStartupPopups: true

# don't display a confirmation when subprocess terminates.
promptToReturnFromSubprocess: false

git:
  # do not spawn a separate process when using GPG
  overrideGpg: true
