require("core.globals")
require("core.options")
require("core.keymaps")
require("core.autocmds")
require("core.lsp")

require("plugins.blink-cmp")
require("plugins.conform")
require("plugins.flash")
require("plugins.lualine")
require("plugins.mini")
require("plugins.nvim-treesitter")
require("plugins.nvim-ts-autotag")
require("plugins.smear-cursor")
require("plugins.snacks")
require("plugins.trouble")
require("plugins.vague")
require("plugins.which-key")
