alias super-tail="tail -f $HOME/Code/*/log/development.log | bat --paging=never -l log"
alias super-tail-groups="tail -f $HOME/Code/{api,church-center,groups,people}/log/development.log | bat --paging=never -l log"

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
source $HOME/pco-box/env.sh
