# https://spaceship-prompt.sh/options/

ZSH_THEME="spaceship"
SPACESHIP_CHAR_SYMBOL="$ "
SPACESHIP_GIT_BRANCH_COLOR="yellow"
SPACESHIP_GIT_STATUS_COLOR="yellow"
SPACESHIP_GIT_STATUS_PREFIX=" {"
SPACESHIP_GIT_STATUS_SUFFIX="}"
SPACESHIP_NODE_SYMBOL="🟢 "
SPACESHIP_RUBY_SYMBOL="💎 "
SPACESHIP_BATTERY_SYMBOL_FULL="🔋 "
SPACESHIP_HOST_PREFIX="💻 "
SPACESHIP_PROMPT_ORDER=(
  dir
  host
  git
  line_sep
  exec_time
  battery
  exit_code
  char
)
