export VISUAL="nvim"
export EDITOR="$VISUAL"

export LANG="en_US.UTF-8"
export LC_ALL="$LANG"

export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=1000
export SAVEHIST=1000
export SHELL_SESSIONS_DISABLE=1

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

export DOT="$HOME/.dotfiles"

export DIRENV_LOG_FORMAT=$'\033[2mdirenv: %s\033[0m' # faint color

export HOMEBREW_BUNDLE_NO_LOCK=1
export HOMEBREW_NO_ANALYTICS=1

export CLAUDE_CONFIG_DIR="$XDG_CONFIG_HOME/claude"

# fzf theme: catppuccin-mocha
export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#171922,spinner:#F5E0DC,hl:#F38BA8 \
--color=fg:#eef1fc,header:#F38BA8,info:#CBA6F7,pointer:#F5E0DC \
--color=marker:#B4BEFE,fg+:#eef1fc,prompt:#CBA6F7,hl+:#F38BA8 \
--color=selected-bg:#45475A \
--color=border:#313244,label:#eef1fc"

if [[ -d "$HOME/pco-box" ]]; then
  source "$HOME/pco-box/env.sh"
fi

if [[ -e "/opt/homebrew/bin/brew" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

