export LANG="en_US.UTF-8"
export LC_ALL="$LANG"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=1000
export SAVEHIST=999
export SHELL_SESSIONS_DISABLE=1

export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

export VISUAL="nvim"
export EDITOR="$VISUAL"

export DOT="$HOME/.dotfiles"

export CLAUDE_CONFIG_DIR="$XDG_CONFIG_HOME/claude"

export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME="/.config/asdf/tool-versions"
export PATH="${ASDF_DATA_DIR}/shims:$PATH"

export GOPATH="$XDG_DATA_HOME/go"

export HOMEBREW_BUNDLE_NO_LOCK=1
export HOMEBREW_NO_ANALYTICS=1

export DIRENV_LOG_FORMAT=$'\033[2mdirenv: %s\033[0m' # faint color

if [[ -d "$HOME/pco-box" ]]; then
  source "$HOME/pco-box/env.sh"
fi

if [[ -e "/opt/homebrew/bin/brew" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

