export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=1000
export SAVEHIST=999
export SHELL_SESSIONS_DISABLE=1

export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

export EDITOR="nvim"
export VISUAL="nvim"

export DOTFILES="$HOME/.dotfiles"

export HOMEBREW_BUNDLE_NO_LOCK=1

export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"

export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
export ASDF_CONFIG_FILE="$ASDF_DIR/asdfrc"

export PATH="$HOME/bin:$PATH"

source "$ZDOTDIR/.zshenv_include"
