export LANG="en_US.UTF-8"
export LC_ALL="$LANG"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_STATE_HOME="$XDG_CONFIG_HOME/local/state"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=1000
export SAVEHIST=999
export SHELL_SESSIONS_DISABLE=1

export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

export VISUAL="nvim"
export EDITOR="$VISUAL"

export DOT="$HOME/.dotfiles"

export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
export GOPATH="$XDG_DATA_HOME/go"
export HOMEBREW_BUNDLE_NO_LOCK=1
