export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=1000
export SAVEHIST=999

export TERM="xterm-256color"

export EDITOR="code --wait"

export DOTFILES="$HOME/.dotfiles"

export PATH="$HOME/bin:$PATH"

export HOMEBREW_BUNDLE_NO_LOCK=1

export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"

source "$ZDOTDIR/.zshenv_include"
