setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

unsetopt nomatch # allows [ or ] wherever, like rake task args

setopt auto_cd
cdpath=($HOME/Code $HOME/Projects)

fpath=($(brew --prefix)/share/zsh-completions $fpath)
autoload -Uz compinit; compinit

source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh"

bindkey "^[[A" history-search-backward # up arrow
bindkey "^[[B" history-search-forward # down arrow

source "$(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme"
source "$ZDOTDIR/.p10k.zsh"

alias dotedit="cd $DOT && $EDITOR"
alias nv="nvim"
alias nvrs="rm -rf $XDG_CONFIG_HOME/nvim $XDG_DATA_HOME/nvim $XDG_STATE_HOME/nvim $XDG_CACHE_HOME/nvim && $DOT/install --only=link"
alias cat="bat"
alias ls="eza"
alias ll="eza -la --group-directories-first --no-permissions --no-filesize --no-user --no-time -I .DS_Store"
alias llt="ll --tree --git --git-ignore"
alias llr="ll --git-repos"
alias grep="rg"
alias find="fd"

alias r="bin/rails"
alias oc="opencode"
alias gg="lazygit"
alias rnm="rm -rf node_modules"
alias bay="bundle install && yarn install"

alias groups="cd groups" # fixes conflict with coreutils command
alias chat="cd chat" # fixes conflict with modem command
alias calendar="cd calendar" # fixes conflict with unix command

if [[ -d "$HOME/Code/pco" ]]; then
  eval "$($HOME/Code/pco/bin/pco init -)"
fi

if command -v direnv &> /dev/null; then
  eval "$(direnv hook zsh)"
fi

