setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

setopt auto_cd
cdpath=($HOME/Code $HOME/Projects)

fpath=($DOTFILES/gitmodules/zsh-completions/src $fpath)
source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$DOTFILES/gitmodules/spaceship-prompt/spaceship.zsh"

bindkey -v # vi mode
bindkey "^[[A" history-search-backward # up arrow
bindkey "^[[B" history-search-forward # down arrow

autoload -U compinit; compinit

alias c="clear"
alias cat="bat --theme=tokyonight --style=changes,rule,numbers"
alias ls="eza"
alias ll="eza -la --group-directories-first --no-permissions --no-filesize --no-user --no-time -I .DS_Store"
alias llt="ll --tree --git --git-ignore"
alias llr="ll --git-repos"
alias nv="nvim"
alias nvrs="rm -rf $XDG_CONFIG_HOME/nvim $XDG_DATA_HOME/nvim $XDG_STATE_HOME/nvim $XDG_CACHE_HOME/nvim && $DOTFILES/install mac --only=link"
alias lg="lazygit"

alias dotedit="$EDITOR $DOTFILES"

alias rnm="rm -rf node_modules"
alias bay="bundle install && yarn install"

source "$ZDOTDIR/.zshrc_include"
