setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

setopt auto_cd
cdpath=($HOME/Code $HOME/Projects)

fpath=($DOTFILES/gitmodules/zsh-completions/src $fpath)
source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh"
source "$DOTFILES/gitmodules/spaceship-prompt/spaceship.zsh"

bindkey "^[[A" history-search-backward # up arrow
bindkey "^[[B" history-search-forward # down arrow

autoload -U compinit; compinit

alias c="clear"
alias bat="bat --theme=kanagawa-dragon --style=changes,rule,numbers"
alias cat="bat"
alias ls="eza"
alias ll="eza -la --group-directories-first --no-permissions --no-filesize --no-user --no-time -I .DS_Store"
alias llt="ll --tree --git --git-ignore"
alias llr="ll --git-repos"
alias nvim="env TERM=wezterm nvim"
alias nv="nvim"
alias nvrs="rm -rf $XDG_CONFIG_HOME/nvim $XDG_DATA_HOME/nvim $XDG_STATE_HOME/nvim $XDG_CACHE_HOME/nvim"
alias lg="lazygit"

alias dotedit="cd $DOTFILES && $EDITOR"

alias rnm="rm -rf node_modules"
alias bay="bundle install && yarn install"

eval "$DOTFILES/zellij/autostart.zsh"

source "$ZDOTDIR/.zshrc_include"
