// Enforce Rails migration and schema hygiene: never hand-write generated files.
//
// Rails migration IDs are UTC timestamps that determine migration ordering.
// Models that write `db/migrate/*.rb` directly invent IDs like `202610081000`
// (wrong length, wrong order, collisions). The only correct way to create one
// is `bin/rails generate migration`, which stamps the ID automatically.
//
// This plugin denies permission when the agent touches protected files and
// returns a denial message the agent sees, so it self-corrects to the right
// commands:
//
//   - db/migrate/*.rb: creating a new migration by hand is denied. Editing an
//     existing migration is allowed (it still passes through the global
//     "edit: ask" permission rule for human approval).
//   - db/schema.rb / db/structure.sql: always denied. These are generated by
//     Rails; hand edits are clobbered by the next db:migrate.
import { existsSync } from "node:fs";
import { isAbsolute, resolve } from "node:path";
import { Plugin } from "@opencode/plugin";

// Matches paths anywhere in the tree (relative or absolute), so engine
// schemas and non-root databases are covered too.
const MIGRATION_PATH = /(?:^|[\\/])db[\\/]migrate[\\/][^\\/]+\.rb$/;
const SCHEMA_PATH = /(?:^|[\\/])db[\\/]schema\.rb$/;
const STRUCTURE_PATH = /(?:^|[\\/])db[\\/]structure\.sql$/;

const MIGRATION_DENIAL_MESSAGE =
  "Rails migration files must be created by the Rails generator so the " +
  "timestamp ID is generated correctly. Never write db/migrate/*.rb by hand. " +
  "Run `bin/rails generate migration <Name>` (optionally with " +
  "`<type>:<column>` shortcuts), then edit the generated file to fill in the " +
  "change.";

const SCHEMA_DENIAL_MESSAGE =
  "db/schema.rb and db/structure.sql are generated by Rails. Never edit, " +
  "create, or patch them by hand — your changes will be clobbered. " +
  "Change the schema by running `bin/rails generate migration <Name>`, " +
  "editing the generated migration, and running `bin/rails db:migrate`, " +
  "which regenerates the schema. To dump the schema without migrating, use " +
  "`bin/rails db:schema:dump`.";

export default Plugin.define({
  id: "rails.migrations",
  async setup(ctx) {
    await ctx.permission.hook("evaluate", (event) => {
      // Only guard file edits; a configured deny is already final.
      if (event.action !== "edit" || event.effect === "deny") return;

      const targets = event.resources.filter(
        (resource) =>
          MIGRATION_PATH.test(resource) ||
          SCHEMA_PATH.test(resource) ||
          STRUCTURE_PATH.test(resource),
      );
      if (targets.length === 0) return;

      // Schema dumps are never hand-editable, even in a fresh app where the
      // file does not exist yet (generate it with db:migrate / db:schema:dump).
      if (
        targets.some(
          (resource) =>
            SCHEMA_PATH.test(resource) || STRUCTURE_PATH.test(resource),
        )
      ) {
        event.effect = "deny";
        event.message = SCHEMA_DENIAL_MESSAGE;
        return;
      }

      // "Creating" = the migration file does not exist yet on disk. Editing
      // an existing migration is legitimate (with human approval) and passes.
      const base = ctx.location.project.canonical ?? ctx.location.directory;
      const creating = targets.some((resource) => {
        const path = isAbsolute(resource) ? resource : resolve(base, resource);
        return !existsSync(path);
      });
      if (!creating) return;

      event.effect = "deny";
      event.message = MIGRATION_DENIAL_MESSAGE;
    });
  },
});
